<?php

namespace Xm\CovoiturageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EscaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EscaleRepository extends EntityRepository
{
}
